### PR TITLE
Update logdir name

### PR DESCRIPTION
**Pull request by zancas**
I added a little code to make the log dir names be a function of the versions of the software running.
I also factored that code into a helper for readability.

This PR also fixes the regression that @dannasessha noticed I introduced into his `zcash-cli`-call-simplification-design.   Thanks for the idea @dannasessha !

### CODE REVIEW

**Comment by dannasessha** [comment]
I see this! Thanks for the code @zancas ! I'll plan to look this over and offer feedback tomorrow.

**Comment by AloeareV** [comment]
I've got some thoughts on how to debug the CI, mostly along the lines of getting the docker container to run stuff like `echo $PATH` and making the rust error messages more verbose

**Comment by zancas** [comment]
I need to migrate some of the logging code to use this:

https://doc.rust-lang.org/std/fs/fn.create_dir_all.html

That will certainly solve some issues.

**Comment by dannasessha** [comment]
This PR seems to be an extension of #7  with no difference in the base commits.

We could close #7  and preserve all proposed changes in this PR.

**Pull request merged**
