### PR TITLE
complete migration of Option into ident

### PR DESCRIPTION
**Pull request by zancas**
Migrate location of `Option` annotation per discussion.

By moving the annotation into the `ident` we allow for non-terminal Optional fields.

### CODE REVIEW

**Comment by zancas** [comment]
@AloeareV is this ready to merge?

**Comment by zancas** [comment]
@AloeareV ?

**Comment by AloeareV** [comment]
Looking at this code, all of this has been discussed synchronously. Nothing jumps out at me as strange, and it's interfacing fine with the parts of typegen it's intended to. Fantastic! Merging!

**Comment by AloeareV** [comment]
Looking at this code, all of this has been discussed synchronously. Nothing jumps out at me as strange, and it's interfacing fine with the parts of typegen it's intended to. Fantastic! Merging!

**Pull request merged**
